[package]
name = "mqtt-subscriber"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rumqttc = "0.8"
axum = { version = "0.6.19"}
serde = { version = "1.0", features = ["derive", "std"] }
serde_json = "1.0"
